name: Context Flow

on: [push]

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
    - name: Print GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
